# Generated by Django 3.2.9 on 2022-08-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '2 . Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name_plural': '3 . CartItems'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '1 . Profiles'},
        ),
    ]
