# Generated by Django 3.2.9 on 2022-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_subcategory_catogary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catogary',
            options={'verbose_name_plural': '1 . Categories'},
        ),
        migrations.AlterModelOptions(
            name='colorvariant',
            options={'verbose_name_plural': '5 . ColorVariants'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': '7 . Coupons'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3 . Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': '4 . ProductImages'},
        ),
        migrations.AlterModelOptions(
            name='sizevariant',
            options={'verbose_name_plural': '6 . SizeVariants'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '2 . Subcategories'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
