# Generated by Django 3.2 on 2022-08-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': '8 . Coupons'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '7 . Tags'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
