# Generated by Django 3.2 on 2022-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220826_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
